### ISSUE TITLE
Replace the common/log file with a child logger that automatically posts to opbeat

### ISSUE THREAD

**Issue by allanchau** [idearium/idearium-lib#43]
https://github.com/trentm/node-bunyan#logchild

The child logger should automatically log all `log.error` with opbeat.
Perhaps we could have a config item `OPBEAT_LOG_LEVEL` that defaults to `error` that would allow you to log warnings etc in the beta environment? `OPBEAT_LOG_LEVEL=warn`

**Comment by smebberson** [comment]
Hmm, it's an interesting idea. I was kind of trying to have the following logic though:

- Opbeat error means something unplanned.
- Log entries error means something planned, albeit, maybe not good.

An unplanned error usually means application state is unstable, so alerting should be of highest priority. Where as a Log entries error doesn't have the same implications.

Although, we should have better anomaly reporting via Log entries. For better alerting/notification purposes, how would you see your idea working? Also, what's the benefit of it being in Opbeat?

**Comment by allanchau** [comment]
We are kind've doing it that way anyway. At the end of a promise we have `.catch(err => log.error({ err }, 'Some error')` which means the error is unplanned?

I think by alerting us when an error occurs we can fix it before a client finds an issue and we have to search through logentries to find the problem?

Being in Opbeat would just mean all our priority alerts are in one place.

**Comment by allanchau** [comment]
Yeah what about if we turn it off if the environment is `development` or `OPBEAT_LOG_LEVEL=off`?

**Comment by allanchau** [comment]
This can be closed now that we have decided to use opbeat strictly for unplanned errors.
