### ISSUE TITLE
@idearium/log

### ISSUE THREAD

**Issue by allanchau** [idearium/idearium-lib#63]
We need to fix this to speed up development + testing in this library. To do this I think a number of things need to happen:
- [ ] Avoid tests hitting the disk (Use Jest mocks if possible).
- [ ] Remove writing files to disk if possible (Replace bunyan with pico and remove local log file functionality)
- [ ] Improve db connections (use one of the recent kubernetes projects).
- [ ] Improve the MQ connections (this is the main part that times out).

Anything else that I have missed?

**Comment by allanchau** [comment]
@smebberson I'm trying to think about how we can fix the tests for this repo and make it so they don't intermittently break.
What do you think about turning this into a monorepo? That way the tests would be isolated to the individual package (mq tests won't cause others to break).
I was thinking we could use it like this:

- `@idearium/log`
- `@idearium/mq`
- `@idearium/mongo`
- `@idearium/redis`

In our projects we would then call each library individually as needed.
We could also have a top level package that combines all of these so we could use it as we do now? The logic + tests would just be in other packages.

**Comment by smebberson** [comment]
@allanchau, great idea.

**Comment by allanchau** [comment]
@smebberson For the first one I want to try out Pino. I've got a working example with it posting to insight ops, but it is missing some current functionality:
- It doesn't log to a local file (I don't think this is really that useful anyway).
- I haven't included debug so there is no way to filter out logs based on a provided context. I've managed to default the context to the current file path and actually prefer calling the module like this
```javascript
const log = require('@idearium/log');

log.info({
    key: 'key',
    member: {
        member: { password: 'password' },
        password: 'password',
        user: { password: 'password' },
        username: 'test',
    },
    password: 'password',
    token: 'token',
    user: {
        member: { password: 'password' },
        username: 'test',
        password: 'password',
        user: { password: 'password' },
    },
}, 'THIS IS A TEST LOG');
```
```shell
[1558009398260] INFO  (30295 on Allans-MacBook-Pro.local): THIS IS A TEST LOG
    context: "/log/test.js"
    key: "[Redacted]"
    member: {
      "member": {
        "password": "[Redacted]"
      },
      "password": "[Redacted]",
      "user": {
        "password": "[Redacted]"
      },
      "username": "test"
    }
    password: "[Redacted]"
    token: "[Redacted]"
    user: {
      "member": {
        "password": "[Redacted]"
      },
      "username": "test",
      "password": "[Redacted]",
      "user": {
        "password": "[Redacted]"
      }
    }
```

Do you think these are required especially with our new guides on what log levels to use?

**Comment by smebberson** [comment]
@allanchau, I think the debug integration is still required. It makes it easy to get logs from other modules we don't write into our logging system.

**Comment by smebberson** [comment]
@allanchau, just consider, the structure we use to name the log context `app:{something}:{path}` aids in our ability to filter in/out certain logs which can help us keep the noise down. The above doesn't allow us to do this?

**Comment by allanchau** [comment]
> @allanchau, I think the debug integration is still required. It makes it easy to get logs from other modules we don't write into our logging system.

@smebberson Currently the way it has been setup, logs will get piped to a transporter so we don't really need debug to be able to pick up debug logs I think. We could detect if a loglevel wasn't provided (debug log) then set a default.

> @allanchau, just consider, the structure we use to name the log context app:{something}:{path} aids in our ability to filter in/out certain logs which can help us keep the noise down. The above doesn't allow us to do this?

Yeah the purpose of the automated context property was so we wouldn't need to add our own context in, with the new logging guides we shouldn't see much noise anyway? The reason I don't like the way the context currently works is that it is too easy to miss logs and relies on the developer to get the context right. e.g. if a file was copied to another project and the context wasn't properly updated, there might be critical logs that will be missed.

```javascript
// file 1
const log = require('@idearium/log')('app1:test:path');

// file 2 (forgot to change app1 to app 2)
const log = require('@idearium/log')('app1:test:newpath');
```

**Comment by smebberson** [comment]
@allanchau, okay, I'm open to trying an automated context for now in order to remove a road block so that we can get this moving. We can just change it if it doesn't work. I'm keen to break `idearium-lib` up for sure :)

**Comment by allanchau** [comment]
@smebberson Cool, also are you happy with the transport thing? https://github.com/pinojs/pino/blob/master/docs/transports.md
I'm thinking we would create some bin files in `@idearium/log` that would pipe the logs somewhere e.g.
```
// In your application
$ node app.js | tee insightops stackdriver ...
```
I've never used `tee` before, but it seems to do what I want (piping the output into multiple spots)
https://unix.stackexchange.com/questions/41246/how-to-redirect-output-to-multiple-log-files/41249


Alternatively we could wrap Pino in that multi streams plugin and do it all automatically, but they don't recommend that.

**Comment by smebberson** [comment]
@allanchau, yeah, I'm cool with it. Do you know what we would use to get the information into InsightOps?

**Comment by allanchau** [comment]
@smebberson Yeah I created a little test previously that tests Pino and sending to InsightOps. Just need to setup the structure of the monorepo so you can have a review.

**Comment by smebberson** [comment]
@allanchau, AWESOME :) I'm keen.
