### ISSUE TITLE
Log context

### ISSUE THREAD

**Issue by allanchau** [idearium/idearium-lib#8]
It is too easy to accidentally copy a log context between containers.

Doesn't Bunyan come with a default context?

**Comment by smebberson** [comment]
How would a default log context help?

**Comment by smebberson** [comment]
We could probably automatically determine it based on a few ENV variables and directories or something similar...

**Comment by allanchau** [comment]
Oh it changes based on the environment? I thought it was just a kind of path.
Yeah setting it to a default would be good.
